server:
  port: 8080
spring:
  thymeleaf:
     cache: false
pivotal:
  accountsService:
    name: accounts-service
    url: http://accounts-service:8082
  portfolioService:
    name: portfolio-service
    url: http://portfolio-service:8081
  quotesService:
    name: quotes-service
    url: http://quotes-service:8083
  summary:
    quotes: 3
    symbols:
      it: ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
